title: Atul Kumar Soni
# title image: 
theme: jekyll-theme-minimal
logo: assets/IMG_1815 - Copy.jpg
# description: Ph.D. Student

social_links: 
- linkedin,       user_url: "https://www.linkedin.com/in/soni-atul"
